import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { api } from "@/lib/api";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import {
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
} from "recharts";

export const Route = createFileRoute("/reports")({
  component: ReportsPage,
});

type ReportSummary = {
  total_assets: number;
  total_vulnerabilities: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
  average_risk: number;
};

const COLORS = [
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
];

function ReportsPage() {
const [report, setReport] = useState<ReportSummary | null>(null);
const [loading, setLoading] = useState(false);
const [compliance, setCompliance] = useState<any>(null);
const [complianceLoading, setComplianceLoading] = useState(false);
const [aiSummary, setAiSummary] = useState("");
function downloadCompliancePDF() {
    if (!compliance) {
        alert("Load a compliance report first.");
        return;
    }

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text(compliance.framework, 20, 20);

    doc.setFontSize(14);
    doc.text(`Compliance Score: ${compliance.score}%`, 20, 35);

    let y = 55;

    doc.setFontSize(16);
    doc.text("Controls", 20, y);

    y += 10;

    compliance.status.forEach((item: any) => {
        doc.text(`${item.control} - ${item.status}`, 20, y);
        y += 8;
    });

    y += 10;

    doc.text("Recommendations", 20, y);

    y += 10;

    compliance.recommendations.forEach((item: string) => {
        doc.text(`• ${item}`, 20, y);
        y += 8;
    });

    doc.save(`${compliance.framework}.pdf`);
}

  async function generateReport() {
    setLoading(true);

    try {
      
    const { data } = await api.get("/reports/summary");
    setReport(data);

    const ai = await api.get("/reports/ai-summary");
    setAiSummary(ai.data.summary);

    } catch (err) {
      console.error(err);
      alert("Unable to generate report.");
    } finally {
      setLoading(false);
    }
  }
  async function loadCompliance(framework: string) {
    setComplianceLoading(true);

    try {
        const { data } = await api.get(
            `/reports/compliance/${framework}`
        );

        setCompliance(data);
        setAiSummary(data.ai_summary);
    } catch (err) {
        console.error(err);
        alert("Unable to load compliance report.");
    } finally {
        setComplianceLoading(false);
    }
}

  function downloadPDF() {
    if (!report) {
      alert("Generate a report first.");
      return;
    }

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("AegisAI ASM", 20, 20);

    doc.setFontSize(16);
    doc.text("Executive Security Report", 20, 32);

    doc.setFontSize(11);
    doc.text(
      `Generated: ${new Date().toLocaleString()}`,
      20,
      42
    );

    autoTable(doc, {
      startY: 55,
      head: [["Metric", "Value"]],
      body: [
        ["Total Assets", report.total_assets],
        ["Total Vulnerabilities", report.total_vulnerabilities],
        ["Critical", report.critical],
        ["High", report.high],
        ["Medium", report.medium],
        ["Low", report.low],
        ["Average Risk", report.average_risk],
      ],
    });

    doc.setFontSize(10);
    doc.text(
      "Generated by AegisAI Attack Surface Management",
      20,
      285
    );

    doc.save("AegisAI_Executive_Report.pdf");
  }

  const total = report?.total_vulnerabilities || 1;

  const severityData = report
    ? [
        {
          name: "Critical",
          value: report.critical,
        },
        {
          name: "High",
          value: report.high,
        },
        {
          name: "Medium",
          value: report.medium,
        },
        {
          name: "Low",
          value: report.low,
        },
      ]
    : [];

  return (
    <AppShell
      title="Executive Reports"
      subtitle="Generate security and compliance reports"
    >
      <div className="grid gap-6">
        <div className="rounded-xl border border-border bg-card p-6">
          <h2 className="text-2xl font-semibold">Executive Security Report</h2>

          <p className="mt-2 text-muted-foreground">
            Summary of assets, vulnerabilities, overall exposure and
            organizational risk posture.
          </p>

          <div className="mt-6 flex flex-wrap gap-4">
            <button
              onClick={generateReport}
              disabled={loading}
              className="rounded-lg bg-primary px-6 py-3 text-primary-foreground disabled:opacity-50"
            >
              {loading ? "Generating..." : "Generate Report"}
            </button>

            <button
              onClick={downloadPDF}
              className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition hover:opacity-90"
            >
              Download Executive PDF
            </button>
          </div>

          {report && (
            <>
              <div className="mt-10">
                <h3 className="mb-6 text-xl font-semibold">Executive Summary</h3>

                <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
                  <div className="rounded-xl border border-border bg-secondary/30 p-5">
                    <p className="text-sm text-muted-foreground">Total Assets</p>
                    <h2 className="mt-2 text-4xl font-bold">{report.total_assets}</h2>
                  </div>

                  <div className="rounded-xl border border-border bg-secondary/30 p-5">
                    <p className="text-sm text-muted-foreground">Vulnerabilities</p>
                    <h2 className="mt-2 text-4xl font-bold">
                      {report.total_vulnerabilities}
                    </h2>
                  </div>

                  <div className="rounded-xl border border-border bg-secondary/30 p-5">
                    <p className="text-sm text-muted-foreground">High Severity</p>
                    <h2 className="mt-2 text-4xl font-bold text-orange-400">
                      {report.high}
                    </h2>
                  </div>

                  <div className="rounded-xl border border-border bg-secondary/30 p-5">
                    <p className="text-sm text-muted-foreground">Average Risk</p>
                    <h2 className="mt-2 text-4xl font-bold text-cyan-400">
                      {report.average_risk.toFixed(2)}
                    </h2>
                  </div>
                </div>
              </div>

              <div className="mt-6 rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-6">
                <h3 className="text-xl font-semibold text-cyan-400">
                  AI Executive Summary
                </h3>

                <p className="mt-4 leading-8 text-muted-foreground">
    {compliance?.ai_summary || aiSummary}
</p>
              </div>

              <div className="mt-10 rounded-xl border border-border bg-card p-6">
                <h3 className="mb-6 text-xl font-semibold">Severity Distribution</h3>

                <div className="grid gap-8 lg:grid-cols-2">
                  <div className="h-[320px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie
                          data={severityData}
                          dataKey="value"
                          nameKey="name"
                          outerRadius={110}
                          label
                        >
                          {severityData.map((_entry, index) => (
                            <Cell key={index} fill={COLORS[index]} />
                          ))}
                        </Pie>

                        <Tooltip />
                        <Legend />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>

                  <div className="space-y-6">
                    <div>
                      <div className="flex justify-between">
                        <span>Critical</span>
                        <span>{report.critical}</span>
                      </div>

                      <div className="mt-2 h-3 w-full overflow-hidden rounded bg-secondary">
                        <div
                          className="h-3 rounded bg-red-500"
                          style={{
                            width: `${Math.min((report.critical / total) * 100, 100)}%`,
                          }}
                        />
                      </div>
                    </div>

                    <div>
                      <div className="flex justify-between">
                        <span>High</span>
                        <span>{report.high}</span>
                      </div>

                      <div className="mt-2 h-3 w-full overflow-hidden rounded bg-secondary">
                        <div
                          className="h-3 rounded bg-orange-500"
                          style={{
                            width: `${Math.min((report.high / total) * 100, 100)}%`,
                          }}
                        />
                      </div>
                    </div>

                    <div>
                      <div className="flex justify-between">
                        <span>Medium</span>
                        <span>{report.medium}</span>
                      </div>

                      <div className="mt-2 h-3 w-full overflow-hidden rounded bg-secondary">
                        <div
                          className="h-3 rounded bg-yellow-500"
                          style={{
                            width: `${Math.min((report.medium / total) * 100, 100)}%`,
                          }}
                        />
                      </div>
                    </div>

                    <div>
                      <div className="flex justify-between">
                        <span>Low</span>
                        <span>{report.low}</span>
                      </div>

                      <div className="mt-2 h-3 w-full overflow-hidden rounded bg-secondary">
                        <div
                          className="h-3 rounded bg-green-500"
                          style={{
                            width: `${Math.min((report.low / total) * 100, 100)}%`,
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-10 rounded-xl border border-border bg-card p-6">
                <h3 className="text-xl font-semibold">AI Recommendations</h3>

                <div className="mt-5 space-y-4">
                  <div className="rounded-lg border border-orange-500/30 bg-orange-500/10 p-4">
                    <p className="font-semibold text-orange-400">Overall Risk Level</p>

                    <p className="mt-2 text-sm text-muted-foreground">
                      {report.high > 5
                        ? "High number of high severity vulnerabilities detected. Immediate remediation is recommended."
                        : "Current security posture is acceptable. Continue monitoring and patch regularly."}
                    </p>
                  </div>

                  <div className="rounded-lg border border-cyan-500/30 bg-cyan-500/10 p-4">
                    <p className="font-semibold text-cyan-400">Recommended Action</p>

                    <p className="mt-2 text-sm text-muted-foreground">
                      Patch vulnerable software, disable unnecessary services,
                      enforce Multi-Factor Authentication (MFA), regularly update
                      operating systems, monitor exposed assets continuously, and
                      perform periodic vulnerability scans.
                    </p>
                  </div>
                </div>
              </div>
            </>
          )}
        </div>

        <div className="rounded-xl border border-border bg-card p-6">
          <h2 className="text-xl font-semibold">Compliance Reports</h2>

          <div className="mt-5 flex flex-wrap gap-4">
            <button
              onClick={() => loadCompliance("iso27001")}
              className="rounded-lg border px-5 py-3 transition hover:bg-primary hover:text-white"
            >
              ISO 27001
            </button>

            <button
              onClick={() => loadCompliance("soc2")}
              className="rounded-lg border px-5 py-3 transition hover:bg-primary hover:text-white"
            >
              SOC 2
            </button>

            <button
              onClick={() => loadCompliance("pci")}
              className="rounded-lg border px-5 py-3 transition hover:bg-primary hover:text-white"
            >
              PCI-DSS
            </button>

            <button
              onClick={() => loadCompliance("owasp")}
              className="rounded-lg border px-5 py-3 transition hover:bg-primary hover:text-white"
            >
              OWASP
            </button>
          </div>
          {compliance && (
            <button
                onClick={downloadCompliancePDF}
                className="mt-5 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition hover:opacity-90"
            >
                Download compliance  PDF
            </button>
)}
          {complianceLoading && (
            <div className="mt-6 rounded-xl border border-border bg-card p-6">
              <p className="text-muted-foreground">Loading compliance report...</p>
            </div>
          )}

          {compliance && (
            <div className="mt-6 space-y-6">
              <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-6">
                <h3 className="text-xl font-semibold text-cyan-400">
                  AI Executive Summary
                </h3>

                <p className="mt-4 leading-8 text-muted-foreground">{aiSummary}</p>
              </div>

              <div className="rounded-xl border border-border bg-secondary/20 p-6">
                <div className="flex items-center justify-between gap-4">
                  <h3 className="text-xl font-semibold">{compliance.framework}</h3>
                  <span className="text-2xl font-bold text-cyan-400">
                    {compliance.score}%
                  </span>
                </div>

                <p className="mt-2 text-sm text-muted-foreground">
                  Compliance score overview
                </p>

                <h4 className="mt-8 mb-4 text-lg font-semibold">Controls</h4>

                <div className="space-y-3">
                  {compliance.status.map((item: any) => (
                    <div
                      key={item.control}
                      className="flex items-center justify-between rounded-lg border border-border p-4"
                    >
                      <span>{item.control}</span>

                      <span
                        className={
                          item.status === "PASS"
                            ? "font-semibold text-green-500"
                            : "font-semibold text-orange-500"
                        }
                      >
                        {item.status}
                      </span>
                    </div>
                  ))}
                </div>

                <h4 className="mt-8 mb-4 text-lg font-semibold">Recommendations</h4>

                <ul className="list-disc space-y-2 pl-6">
                  {compliance.recommendations.map((item: string) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </div>
      </div>
    </AppShell>
  );
}